apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-hello-build-pipeline
  labels:
    app: quarkus-hello
spec:
  params:
    - name: git-repository-url
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-repository-url)
      workspaces:
        - name: output
          workspace: workspace
  workspaces:
    - name: workspace